CREATE DATABASE AV2
GO
USE AV2
GO
CREATE TABLE TIMES
(
CODIGOTIME	INT			NOT NULL,
NOMETIME	VARCHAR(50)	NOT NULL,
CIDADE		VARCHAR(50)	NOT NULL,
ESTADIO		VARCHAR(50)	NOT NULL,
MATERIALE	VARCHAR(50)	NOT NULL
PRIMARY KEY (CODIGOTIME)
)
GO
CREATE TABLE GRUPO
(
GRP			CHAR(01)	NOT NULL,
TIMECOD		INT			NOT NULL
PRIMARY KEY (GRP,TIMECOD)
FOREIGN KEY (TIMECOD)
			REFERENCES TIMES (CODIGOTIME)
)
GO
CREATE TABLE JOGOS
(
CODIGOTIMEA	INT			NOT NULL,
CODIGOTIMEB	INT			NOT NULL,
GOLSTIMEA	INT			NOT NULL,
GOLSTIMEB	INT			NOT NULL,
DATA		DATE		NOT NULL
)
GO
ALTER TABLE JOGOS
ADD CONSTRAINT CON1 PRIMARY KEY(CODIGOTIMEA,CODIGOTIMEB)
GO
CREATE TABLE PRO_GRPR
(
NUMRAND		INT			NOT NULL,
TIMEN		VARCHAR(50) NOT NULL,
GRP			CHAR(01)	NOT NULL,
INDEXGRP	INT			NOT NULL
PRIMARY KEY (NUMRAND)
)
GO
CREATE TABLE GRUPOSNOME
(
ID			INT			NOT NULL,
NOME		CHAR(01)	NOT NULL
PRIMARY KEY (ID)
)
GO
CREATE TABLE MATCHES
(
ID		INT			NOT NULL,
RDS		VARCHAR(20) NOT NULL
PRIMARY KEY (ID)
)
GO
INSERT INTO MATCHES
VALUES
(1,'ADBC'),
(2,'BDAC'),
(3,'CDAB')
GO
INSERT INTO GRUPOSNOME
VALUES
(1,'A'),
(2,'B'),
(3,'C'),
(4,'D')
GO
INSERT INTO TIMES
VALUES
(1,'AGUA SANTA','DIADEMA','DISTRITAL DO INAMAR','KARLIU'),
(2,'BOTAFOGO-SP','RIBEIRAO PRETO','SANTA CRUZ','VOLT SPORT'),
(3,'CORINTHIAS','SAO PAULO','NEO QUIMICA ARENA','NIKE'),
(4,'FERROVIARIA','ARARAQUARA','FONTE LUMINOSA','LUPO'),
(5,'GUARANI','CAMPINAS','BRINCO DE OURO','KAPPA'),
(6,'INTER DE LIMEIRA','LIMEIRA','LIMEIRAO','ALLURI SPORTS'),
(7,'ITUANO','ITU','NOVELLI JUNIOR','KANZA'),
(8,'MIRASSOL','MIRASSOL','JOSE MARIA DE CAMPOS MAIA','SUPER BOLLA'),
(9,'NOVORIZONTINO','NOVO HORIZONTE','JORGE ISMAEL DE BIASI','PHYSICUS'),
(10,'PALMEIRAS','SAO PAULO','ALLIANZ PARQUE','PUMA'),
(11,'PONTE PRETA','CAMPINAS','MOISES LUCARELLI','1900'),
(12,'RED BULL BRAGANTINO','BRAGANCA PAULISTA','NABI ABI CHEDID','NIKE'),
(13,'SANTO ANDRE','SANTO ANDRE','BRUNO JOSE DANIEL','ICONE SPORTS'),
(14,'SANTOS','SANTOS','VILA BELMIRO','UMBRO'),
(15,'SAO BERNARDO','SAO BERNARDO DO CAMPO','PRIMEIRO DE MAIO','MAGNUM GROUP'),
(16,'SAO PAULO','SAO PAULO','MORUMBI','ADIDAS')
GO
CREATE PROCEDURE SP_INSERTEAM @RAND INT,@TEAM VARCHAR(50),@GROUP CHAR(01),@IX INT
AS
	INSERT INTO PRO_GRPR
	VALUES
	(@RAND,@TEAM,@GROUP,@IX)
	INSERT INTO GRUPO
	VALUES
	(@GROUP,(SELECT T.CODIGOTIME FROM TIMES T WHERE T.NOMETIME = @TEAM))
GO
CREATE PROCEDURE PRO11
AS
	DECLARE @I			INT,
			@RNUM		INT,
			@GRPINDEX	INT,
			@GNOME		CHAR(01),
			@GITEMINDEX	INT,
			@TIMENOME	VARCHAR(50)
	SET @I = 1
	SET @RNUM = 0
	SET @TIMENOME = ''
	SET @GRPINDEX = 1
	SET @GNOME = ''
	SET @GITEMINDEX =1
	WHILE (@I <= 16)
	BEGIN
		SET @RNUM = (RAND()*16)+1
		SET @TIMENOME = (SELECT T.NOMETIME FROM TIMES T WHERE T.CODIGOTIME = @RNUM)
		SET @GNOME = (SELECT GP.NOME FROM GRUPOSNOME GP WHERE GP.ID = @GRPINDEX)
		IF((@I%4)!= 0)
		BEGIN
			--(SELECT T.NOMETIME FROM TIMES T WHERE T.CODIGOTIME = @RNUM)
			--Coritnthians, Palmeiras, Santos e São Paulo
			IF(@TIMENOME NOT LIKE '%CORINTHIAS%' AND @TIMENOME NOT LIKE '%PALMEIRAS%'AND @TIMENOME NOT LIKE '%SANTOS%' AND
			@TIMENOME NOT LIKE '%SAO PAULO%')
			BEGIN
				--(SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.TIMEN = @TIMENOME)
				IF ((SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.TIMEN = @TIMENOME) IS NULL)
				BEGIN
					EXEC SP_INSERTEAM @RNUM,@TIMENOME,@GNOME,@GITEMINDEX
					SET @I = @I + 1
					SET @GITEMINDEX = @GITEMINDEX + 1
				END
			END
		END
		ELSE
		BEGIN
			IF(@TIMENOME LIKE '%CORINTHIAS%' OR @TIMENOME LIKE '%PALMEIRAS%' OR @TIMENOME LIKE '%SANTOS%' OR
			@TIMENOME LIKE '%SAO PAULO%')
			BEGIN
				IF ((SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.TIMEN = @TIMENOME) IS NULL)
				BEGIN
					--(SELECT GP.NOME FROM GRUPOSNOME GP WHERE GP.ID = @GRPINDEX)
					--INSERT INTO PRO_GRPR VALUES (@RNUM,@TIMENOME,@GNOME,@GRPINDEX)
					EXEC SP_INSERTEAM @RNUM,@TIMENOME,@GNOME,@GITEMINDEX
					SET @GRPINDEX = @GRPINDEX + 1
					SET @I = @I + 1
					SET @GITEMINDEX = 1
				END
			END
		END
	END
--------------------------------------------------------------------------------------------------------------------------------------------------
GO
CREATE PROCEDURE RODADASJOGO
AS
	DECLARE @GRPRODADA INT,
			@GRPPARTIDA INT,
			@GRPPARTIDA2 INT,
			@TEAM1		VARCHAR(50),
			@TEAM2		VARCHAR(50),
			@TEAMMATCH  VARCHAR(20),
			@IJOGO		INT,
			@VIC		INT,
			@GOLS1		INT,
			@DIAS		DATE,
			@DIASEMANA  INT,
			@CORE		INT,
			@GOLS2		INT,
			@RODADAS	INT

	SET @GRPRODADA = 1
	SET @GRPPARTIDA2 = 1
	SET @GRPPARTIDA = 1
	SET @TEAMMATCH = ''
	SET @IJOGO = 1
	-----------------
	SET @VIC = 0
	-----------------
	SET @GOLS1 = 0
	SET @GOLS2 = 0
	SET @DIAS = GETDATE()
	SET @DIASEMANA = DATEPART(WEEKDAY,@DIAS)
	SET @CORE = 0
	--SET @RODADAS = 1
	WHILE (@GRPRODADA <= 3)
	BEGIN
		SET @TEAMMATCH = (SELECT M.RDS FROM MATCHES M WHERE M.ID = @GRPRODADA)
		WHILE (@GRPPARTIDA2<=4)
		BEGIN
--------------------------------------------------------------------------------------------------------------------------------------------------
			WHILE (@DIASEMANA != 1 AND @DIASEMANA != 4)
			BEGIN
				--SET @DIAS = CONVERT(VARCHAR(11),DATEADD(DAY,1,@DIAS))
				--PRINT(CONVERT(VARCHAR(11),@DIAS))
				--PRINT(@DIASEMANA)
				SET @DIAS = DATEADD(DAY,1,@DIAS)
				SET @DIASEMANA = DATEPART(WEEKDAY,@DIAS)
			END
			--PRINT('OK')
			WHILE (@GRPPARTIDA<=4)
			BEGIN
				WHILE(@IJOGO <= 3)
				BEGIN
					SET @TEAM1 = (SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.GRP = SUBSTRING(@TEAMMATCH,@IJOGO,1) 
					AND PG.INDEXGRP = @GRPPARTIDA)

					IF(@VIC+@GRPPARTIDA >= 5)
					BEGIN
						SET @TEAM2 = (SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.GRP = SUBSTRING(@TEAMMATCH,(@IJOGO+1),1) 
						AND PG.INDEXGRP = (@GRPPARTIDA+@VIC)-4)
					END
					ELSE
					BEGIN
						SET @TEAM2 = (SELECT PG.TIMEN FROM PRO_GRPR PG WHERE PG.GRP = SUBSTRING(@TEAMMATCH,(@IJOGO+1),1) 
						AND PG.INDEXGRP = @GRPPARTIDA+@VIC)
					END
					------------
					SET @GOLS1 = (RAND()*4)
					SET @GOLS2 = (RAND()*4)
					--PRINT(@TEAM1)
					--PRINT(@TEAM2)
					INSERT INTO JOGOS
					VALUES
					((SELECT T.CODIGOTIME FROM TIMES T WHERE T.NOMETIME = @TEAM1),
					(SELECT T.CODIGOTIME FROM TIMES T WHERE T.NOMETIME = @TEAM2),
					@GOLS1,@GOLS2,@DIAS
					)
					------------
					SET @IJOGO = @IJOGO + 2
				END
				SET @IJOGO = 1
				SET @GRPPARTIDA = @GRPPARTIDA+1
				--SET @RODADAS = @RODADAS + 1
			END
		--SET @DIAS = CONVERT(VARCHAR(11),DATEADD(DAY,1,@DIAS))
		--PRINT(@DIAS)
		SET @DIAS = DATEADD(DAY,1,@DIAS)
		SET @DIASEMANA = DATEPART(WEEKDAY,@DIAS)
--------------------------------------------------------------------------------------------------------------------------------------------------
		-------------------------
		PRINT(@VIC)
		SET @VIC = @VIC+1
		--------------------------
		SET @GRPPARTIDA = 1
		SET @GRPPARTIDA2 = @GRPPARTIDA2+1
		END
		--------------------------
		SET @VIC = 0
		--------------------------
		SET @GRPPARTIDA2 = 1
		SET @GRPRODADA = @GRPRODADA+1
	END
GO
CREATE PROCEDURE INITIAL
AS
	DELETE FROM JOGOS
	DELETE FROM GRUPO
	DELETE FROM PRO_GRPR
	EXEC PRO11
	EXEC RODADASJOGO
------------------------------
GO
----------------------------------------------------------------------------------------------------------------------------------------------------
EXEC INITIAL
GO
--01 TABELA GRUPOS
SELECT T.NOMETIME,G.GRP FROM GRUPO G INNER JOIN TIMES T ON T.CODIGOTIME = G.TIMECOD WHERE G.GRP LIKE 'A'
GO
--02 TIMES
SELECT T.NOMETIME,T.CIDADE,T.ESTADIO,T.MATERIALE FROM TIMES T ORDER BY T.NOMETIME
--03 RODADAS
GO
SELECT T1.NOMETIME AS TIME_A,J.GOLSTIMEA,T2.NOMETIME AS TIME_B,J.GOLSTIMEB  FROM JOGOS J INNER JOIN TIMES T1 ON 
J.CODIGOTIMEA = T1.CODIGOTIME INNER JOIN TIMES T2 ON T2.CODIGOTIME = J.CODIGOTIMEB
WHERE CONVERT(VARCHAR(12),J.DATA,31) = '2023-26-03'

USE MASTER
GO
DROP DATABASE AV2